# Generated by Django 5.2.2 on 2025-07-23 08:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='referral_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='downloads_this_month',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_premium_subscriber',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_month_reset',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='monthly_download_limit',
            field=models.PositiveIntegerField(default=50, help_text='Monthly download limit for free users'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='premium_subscription_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='signup_bonus_awarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='token_balance',
            field=models.PositiveIntegerField(default=50, help_text='Current token balance'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_tokens_earned',
            field=models.PositiveIntegerField(default=50, help_text='Total tokens earned over time'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_tokens_spent',
            field=models.PositiveIntegerField(default=0, help_text='Total tokens spent on downloads'),
        ),
        migrations.CreateModel(
            name='TokenPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.CharField(choices=[('basic', '100 Tokens - $10'), ('standard', '500 Tokens - $40'), ('premium', '1200 Tokens - $80'), ('mega', '3000 Tokens - $150')], max_length=20)),
                ('tokens_purchased', models.PositiveIntegerField()),
                ('usd_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=10)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_purchases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
