# Generated by Django 5.2.2 on 2025-07-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_referral_code_customuser_referred_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='referral_code',
            field=models.CharField(blank=True, help_text='Unique referral code for the user', max_length=10, null=True, unique=True),
        ),
    ]
