name: Django CI Debug
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"
      
      - name: Debug - Show current directory
        run: |
          echo "Current working directory:"
          pwd
          echo ""
          echo "Contents of root directory:"
          ls -la
          echo ""
          echo "Contents of afridata directory:"
          ls -la afridata/ || echo "afridata directory does not exist"
          echo ""
          echo "Find all requirements.txt files:"
          find . -name "requirements.txt" -type f
          echo ""
          echo "Tree structure (if available):"
          tree -a || echo "tree command not available"
      
      - name: Check if requirements.txt exists in afridata
        run: |
          if [ -f "afridata/requirements.txt" ]; then
            echo "requirements.txt found in afridata/"
            echo "Contents:"
            cat afridata/requirements.txt
          else
            echo "requirements.txt NOT found in afridata/"
          fi
      
      - name: Try installing from afridata/requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r afridata/requirements.txt
        continue-on-error: true
      
      - name: Try installing from working directory
        working-directory: ./afridata
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        continue-on-error: true
